SocialNetwork/SocialNetwork/Controllers/AccountDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialNetwork.Models;
using SocialNetwork.Models.ViewModel;
using System.IO;

namespace SocialNetwork.Controllers
{
    public class AccountDetailController : Controller
    {
        AccountDetailModels accountDetailModel = new AccountDetailModels();
        // GET: AccountDetail
        public ActionResult Profile(int id)
        {
            User user = accountDetailModel.GetUserById(id);
            Session["User"] = user;
            //ViewData["Favorites"] = accountDetailModel.GetListFavoriteByUserId(user.userId);
            return View(user);
        }
        [HttpPost]
        public ActionResult UpdateProfile(User model)
        {
            accountDetailModel.UpdateUser(model);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ChangePass(ChangePassViewModel model)
        {


            if (model.password == null)
                return View();
            else
            {
                User user = (User)System.Web.HttpContext.Current.Session["User"];
                if (accountDetailModel.ChangePass(model, user.userId))
                    return RedirectToAction("Profile", new {id=user.userId });
                else
                    return View();
            }
        }

        public ActionResult ChangeAvatar(int userId)
        {
            string linkImage = "";
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                // Get the uploaded image from the Files collection
                var httpPostedFile = System.Web.HttpContext.Current.Request.Files["UploadedImage"];

                if (httpPostedFile != null)
                {
                    var fileSavePath = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/images/Avatar"), httpPostedFile.FileName);
                    httpPostedFile.SaveAs(fileSavePath);
                }
                linkImage = "/Content/images/Avatar/" + httpPostedFile.FileName;

            }
            string linkAvatarold = accountDetailModel.updateAvatarUser(userId, linkImage);
            //linkAvatarold = linkAvatarold.Replace("/", "\\");
            //string folder = @"C:\Users\HuyPV\Documents\Visual Studio 2013\Projects\SocialNetwork\SocialNetwork";

            //linkAvatarold = folder + linkAvatarold;
            //if (System.IO.File.Exists(linkAvatarold))
            //{ System.IO.File.Delete(linkAvatarold); }
            return RedirectToAction("Profile", new { id = userId });
        }
    }
}

SocialNetwork/SocialNetwork/Views/AccountDetail/ChangePass.cshtml
@model SocialNetwork.Models.ViewModel.ChangePassViewModel
@{
    ViewBag.Title = "ChangePass";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

    @using (Html.BeginForm("ChangePass", "AccountDetail", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h2 style="margin-top:70px">ChangePass</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m._password, new { @class = "col-md-4 control-label", style = "text-align: left;" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m._password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model._password, "", new { @class = "text-warning" })
                </div>
            </div>
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.password, new { @class = "col-md-4 control-label", style = "text-align: left;" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m.password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-warning" })
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-4 control-label", style = "text-align: left;" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-warning" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Thay đổi" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

SocialNetwork/SocialNetwork/Views/AccountDetail/Profile.cshtml
@model SocialNetwork.Models.User

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@Styles.Render("~/bundles/css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/Content/js/JavaScript.js"></script>
<link href="~/Content/Style.css" rel="stylesheet" />
<h4>Thiết lập tài khoản</h4>

@using (Html.BeginForm("UpdateProfile", "AccountDetail", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
    <div class="profile">
        <table>
            <tr>
                <td class="col_1"><span>Ảnh đại diện</span></td>
                <td class="col_2">
                    <img class="img-thumbnail img-responsive" id="image_change_avatar" src="@Html.DisplayFor(model => model.avatar)" style="height:100px;width:100px" />
                    <input type="file" id="change_avatar" value="chọn ảnh" style="display:inline-block" class="btn btn-sm btn-info" />
                    
                </td>
                <td class="col_3">
                    
                    <input type="button" onclick="updateAvatar(@Html.DisplayFor(model => model.userId))" id="idUpdateAvatar" style="display:none" class="btn btn-sm btn-info" value="Thay đổi" />
                    <input type="button" onclick="undoAvatar()" class="btn btn-sm btn-info" value="Hủy" id="idUndoAvatar" style="display:none" />
                </td>
            </tr>
            <tr>
                <td class="col_1"><span>Tên người dùng</span></td>
                <td class="col_2"><span>@Html.EditorFor(model => model.nickName, new { htmlAttributes = new { @class = "form-control" } })</span></td>
                <td class="col_3"></td>
            </tr>
            <tr>
                <td class="col_1"><span>Mật khẩu</span></td>
                <td class="col_2"></td>
                <td class="col_3">
                    
                    @Html.ActionLink("Đổi mật khẩu", "ChangePass")
                </td>

            </tr>
            <tr>
                <td class="col_1"><span>Số điện thoại</span></td>
                <td class="col_2"><span>@Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })</span></td>
                <td class="col_3"></td>
            </tr>
            <tr>
                <td class="col_1"><span>Ngày sinh</span></td>
                <td class="col_2"><span>@Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control" } })</span></td>
                <td class="col_3"></td>
            </tr>
            <tr>
                <td class="col_1"><span>Quốc gia</span></td>
                <td class="col_2"><span>@Html.EditorFor(model => model.Addr.Country.countryName, new { htmlAttributes = new { @class = "form-control" } })</span></td>
                <td class="col_3"></td>
            </tr>
            <tr>
                <td class="col_1"><span>Tỉnh/Thành phố</span></td>
                <td class="col_2"><span>@Html.EditorFor(model => model.Addr.Country.County.countyName, new { htmlAttributes = new { @class = "form-control" } })</span></td>
                <td class="col_3"></td>
            </tr>
            <tr>
                <td colspan="3">
                    <input type="submit" value=" Hoàn Thành" class="btn btn-sm btn-info" />
                </td>
            </tr>
        </table>
    </div>
    <span style="display:none">@Html.EditorFor(model=> model.userId)</span>
}